name: math_study_app
description: Math study app v0.6.1-beta
publish_to: "none"
version: 0.6.1-beta+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  sqflite: ^2.2.5
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  signature: ^5.2.0
  lottie: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
